In [20]:
import matplotlib.pyplot as plt
import numpy as np
def sigmoid(x):
    return(1/1+np.exp(-x))
def sigmoid

class Dense_layer():
    def __init__(self,n_inputs,n_neurons):
        self.n_inputs=n_inputs
        self.n_neurons=n_neurons
        self.weights = np.random.randn(n_neurons, n_inputs) * 0.1 #intialize weights and biases with random numbers(use normal distribution)
        self.biases=np.zeros(n_neurons)
    def activations(self,x):
        return sigmoid(np.dot(self.weights,x) + self.biases)

In [5]:
rd_array=np.random.randn(5) # random vector
print(rd_array)

[ 0.05333697 -0.94466747  0.33729453 -0.25642125  1.16019277]


In [6]:
rd_array2=np.random.randn(3,2) # random matrix with 3 rows and 2 columns
print(rd_array2)

[[ 1.04341039 -0.53461654]
 [ 0.94957158 -0.42803692]
 [ 2.09826051  0.51871625]]


In [27]:
class my_nn():
    def __init__(self, lay_sizes):
        self.n_layers = len(lay_sizes)          # total number of layers incl. input
        self.lay_list =[Dense_layer(lay_sizes[i], lay_sizes[i+1]) for i in range(self.n_layers-1)]   # start from 1, skip input layer
nn1=my_nn([2,3,1]) 
for lay in nn1.lay_list:
    print(lay.weights)
    print(lay.biases)

[[-0.03167321  0.01305096]
 [ 0.09754303 -0.06805362]
 [-0.07934193 -0.10692603]]
[0. 0. 0.]
[[0.02469989 0.15850783 0.0363045 ]]
[0.]


In [28]:
def output(self, x, y):
    a = x                          # start with the input
    for layer in self.lay_list:    # go through each layer
        a = layer.activations(a)   # output of this layer becomes input of next
    return a                       # final output is y_hat

In [29]:
def C_prime(self, y_hat, y):
    return y_hat - y

In [30]:
def nabla_C(self, x, y):
    # --- FORWARD PASS: save z and a at every layer ---
    zs = []       # list of z values per layer
    activations = [x]   # list of activations, starting with input x

    a = x
    for layer in self.lay_list:
        z = np.dot(layer.weights, a) + layer.biases
        zs.append(z)
        a = sigmoid(z)
        activations.append(a)

    # --- BACKWARD PASS ---
    # Empty lists to store gradients (one entry per layer)
    nabla_b = [np.zeros(l.biases.shape) for l in self.lay_list]
    nabla_W = [np.zeros(l.weights.shape) for l in self.lay_list]

    # sigmoid derivative
    def sigmoid_prime(z):
        return sigmoid(z) * (1 - sigmoid(z))

    # Start at output layer (index -1)
    y_hat = activations[-1]
    delta = self.C_prime(y_hat, y) * sigmoid_prime(zs[-1])
    nabla_b[-1] = delta
    nabla_W[-1] = np.outer(delta, activations[-2])

    # Work backwards through remaining layers
    for l in range(2, self.n_layer):
        z = zs[-l]
        delta = np.dot(self.lay_list[-l+1].weights.T, delta) * sigmoid_prime(z)
        nabla_b[-l] = delta
        nabla_W[-l] = np.outer(delta, activations[-l-1])

    return nabla_b, nabla_W

In [31]:
def learn(self, training_data, eta=0.1, epochs=10):
    for epoch in range(epochs):
        for x, y in training_data:
            nabla_b, nabla_W = self.nabla_C(x, y)
            for i, layer in enumerate(self.lay_list):
                layer.weights -= eta * nabla_W[i]
                layer.biases  -= eta * nabla_b[i]